SELECT DISTINCT count(distinct ?ensId) as ?UniqueEnsembl #remove 'distinct' to count all ensembl IDs
WHERE {
  ?dataNodes a wp:DataNode ;
  wp:bdbEnsembl ?ensId ;
  dcterms:isPartOf ?pw.
  ?pw a wp:Pathway;
  dc:title ?title ;
  wp:organism ?organism ;
  wp:organismName "Homo sapiens"^^xsd:string .
}
