SELECT DISTINCT count(distinct ?pubmed) as ?pubmedCount #remove 'distinct' to count all ensembl IDs
WHERE {
  ?pubmed a wp:PublicationReference ;
  dcterms:isPartOf ?pathway.
  ?pathway a wp:Pathway;
  wp:organism ?organism ;
  wp:organismName "Homo sapiens"^^xsd:string ;
  wp:ontologyTag ?pwo.
  FILTER (?pwo != cur:Reactome_Approved)
}
